import type { WorkflowRun } from "@/types/workflow";

export const mockWorkflowRuns: WorkflowRun[] = [
  {
    id: "wf-1",
    name: "Customer Support Triage",
    description: "Classify incoming ticket, route to specialist, generate response",
    status: "completed",
    triggeredBy: "Incoming support ticket #4821",
    startedAt: "2026-03-05T14:00:00Z",
    completedAt: "2026-03-05T14:00:47Z",
    totalDurationMs: 47200,
    totalCost: 0.14,
    totalTokens: 8420,
    steps: [
      {
        id: "s1",
        agentId: "triage",
        agentName: "Triage",
        agentEmoji: "🏷️",
        label: "Classify ticket",
        status: "completed",
        startedAt: "2026-03-05T14:00:00Z",
        completedAt: "2026-03-05T14:00:08Z",
        durationMs: 8200,
        input: "User: My payment failed and I was charged twice",
        output: '{"route":"billing","confidence":"high"}',
        model: "gpt-4o-mini",
        tokenUsage: { prompt: 320, completion: 45 },
        cost: 0.01,
        toolCalls: [],
      },
      {
        id: "s2",
        agentId: "billing",
        agentName: "Billing",
        agentEmoji: "💳",
        label: "Investigate billing issue",
        status: "completed",
        startedAt: "2026-03-05T14:00:08Z",
        completedAt: "2026-03-05T14:00:32Z",
        durationMs: 24100,
        input: "Duplicate charge investigation for ticket #4821",
        output: "Found duplicate charge of $49.00. Refund initiated.",
        model: "claude-sonnet-4",
        tokenUsage: { prompt: 1850, completion: 680 },
        cost: 0.08,
        toolCalls: [
          { id: "tc1", name: "LookupUser", status: "completed", durationMs: 120, result: "User #892 found" },
          { id: "tc2", name: "QueryPayments", status: "completed", durationMs: 340, result: "2 charges found for $49.00" },
          { id: "tc3", name: "InitiateRefund", status: "completed", durationMs: 890, result: "Refund #RF-2841 created" },
        ],
      },
      {
        id: "s3",
        agentId: "response",
        agentName: "Response",
        agentEmoji: "✍️",
        label: "Draft customer reply",
        status: "completed",
        startedAt: "2026-03-05T14:00:32Z",
        completedAt: "2026-03-05T14:00:47Z",
        durationMs: 14900,
        input: "Generate empathetic reply about refund for duplicate charge",
        output: "Hi there! I found the duplicate charge and have initiated a refund of $49.00...",
        model: "claude-sonnet-4",
        tokenUsage: { prompt: 2100, completion: 3425 },
        cost: 0.05,
        toolCalls: [
          { id: "tc4", name: "SendEmail", status: "completed", durationMs: 210, result: "Email sent to user@example.com" },
        ],
      },
    ],
    handoffs: [
      {
        id: "h1",
        fromAgentId: "triage",
        fromAgentName: "Triage",
        fromAgentEmoji: "🏷️",
        toAgentId: "billing",
        toAgentName: "Billing",
        toAgentEmoji: "💳",
        reason: "Classified as billing issue (high confidence)",
        context: "Duplicate charge complaint",
        timestamp: "2026-03-05T14:00:08Z",
      },
      {
        id: "h2",
        fromAgentId: "billing",
        fromAgentName: "Billing",
        fromAgentEmoji: "💳",
        toAgentId: "response",
        toAgentName: "Response",
        toAgentEmoji: "✍️",
        reason: "Issue resolved, needs customer communication",
        context: "Refund #RF-2841 initiated for $49.00",
        timestamp: "2026-03-05T14:00:32Z",
      },
    ],
  },
  {
    id: "wf-2",
    name: "Code Review Pipeline",
    description: "Analyze PR, run tests, check security, approve or request changes",
    status: "running",
    triggeredBy: "PR #142 opened by @arushs",
    startedAt: "2026-03-05T14:15:00Z",
    totalDurationMs: undefined,
    totalCost: 0.22,
    totalTokens: 12800,
    steps: [
      {
        id: "s4",
        agentId: "reviewer",
        agentName: "Reviewer",
        agentEmoji: "👀",
        label: "Analyze diff",
        status: "completed",
        startedAt: "2026-03-05T14:15:00Z",
        completedAt: "2026-03-05T14:15:18Z",
        durationMs: 18400,
        input: "Review PR #142: Add rate limiting to API endpoints",
        output: "12 files changed, 3 concerns identified",
        model: "claude-opus-4",
        tokenUsage: { prompt: 4200, completion: 1800 },
        cost: 0.15,
        toolCalls: [
          { id: "tc5", name: "read", status: "completed", durationMs: 45, result: "Read 12 files" },
          { id: "tc6", name: "exec", status: "completed", durationMs: 3200, result: "Tests pass (42/42)" },
        ],
      },
      {
        id: "s5",
        agentId: "security",
        agentName: "Security",
        agentEmoji: "🔒",
        label: "Security scan",
        status: "running",
        startedAt: "2026-03-05T14:15:18Z",
        input: "Scan PR #142 for security vulnerabilities",
        model: "claude-sonnet-4",
        tokenUsage: { prompt: 3800, completion: 3000 },
        cost: 0.07,
        toolCalls: [
          { id: "tc7", name: "exec", status: "completed", durationMs: 5400, result: "Brakeman: 0 warnings" },
          { id: "tc8", name: "exec", status: "running", durationMs: undefined },
        ],
      },
      {
        id: "s6",
        agentId: "reviewer",
        agentName: "Reviewer",
        agentEmoji: "👀",
        label: "Post review",
        status: "pending",
      },
    ],
    handoffs: [
      {
        id: "h3",
        fromAgentId: "reviewer",
        fromAgentName: "Reviewer",
        fromAgentEmoji: "👀",
        toAgentId: "security",
        toAgentName: "Security",
        toAgentEmoji: "🔒",
        reason: "Diff analyzed, passing to security scan",
        context: "Rate limiting changes touch auth middleware",
        timestamp: "2026-03-05T14:15:18Z",
      },
    ],
  },
  {
    id: "wf-3",
    name: "Content Pipeline",
    description: "Research topic, write draft, review, publish",
    status: "failed",
    triggeredBy: "Scheduled: Weekly blog post",
    startedAt: "2026-03-05T10:00:00Z",
    completedAt: "2026-03-05T10:05:30Z",
    totalDurationMs: 330000,
    totalCost: 0.09,
    totalTokens: 5200,
    steps: [
      {
        id: "s7",
        agentId: "researcher",
        agentName: "Researcher",
        agentEmoji: "🔍",
        label: "Research topic",
        status: "completed",
        startedAt: "2026-03-05T10:00:00Z",
        completedAt: "2026-03-05T10:02:15Z",
        durationMs: 135000,
        input: "Research: AI agent frameworks comparison 2026",
        output: "Compiled 8 sources on LangChain, CrewAI, AutoGen, RailsKit",
        model: "gpt-4o",
        tokenUsage: { prompt: 2400, completion: 1800 },
        cost: 0.06,
        toolCalls: [
          { id: "tc9", name: "web_search", status: "completed", durationMs: 1800, result: "8 results" },
          { id: "tc10", name: "web_fetch", status: "completed", durationMs: 2400, result: "Fetched 5 pages" },
        ],
      },
      {
        id: "s8",
        agentId: "writer",
        agentName: "Writer",
        agentEmoji: "📝",
        label: "Write draft",
        status: "failed",
        startedAt: "2026-03-05T10:02:15Z",
        completedAt: "2026-03-05T10:05:30Z",
        durationMs: 195000,
        error: "Context window exceeded — research payload too large (128K tokens)",
        model: "gpt-4o-mini",
        tokenUsage: { prompt: 1000, completion: 0 },
        cost: 0.03,
      },
      {
        id: "s9",
        agentId: "editor",
        agentName: "Editor",
        agentEmoji: "✏️",
        label: "Review & edit",
        status: "skipped",
      },
      {
        id: "s10",
        agentId: "publisher",
        agentName: "Publisher",
        agentEmoji: "📤",
        label: "Publish",
        status: "skipped",
      },
    ],
    handoffs: [
      {
        id: "h4",
        fromAgentId: "researcher",
        fromAgentName: "Researcher",
        fromAgentEmoji: "🔍",
        toAgentId: "writer",
        toAgentName: "Writer",
        toAgentEmoji: "📝",
        reason: "Research complete, handing off for draft",
        context: "8 sources compiled, ~45K tokens of research",
        timestamp: "2026-03-05T10:02:15Z",
      },
    ],
  },
];
