import type { DocumentCollection, Document, SearchResult } from "@/types/rag";

export const mockCollections: DocumentCollection[] = [
  {
    id: "col-1",
    name: "Product Documentation",
    description: "API docs, guides, and tutorials for the main product.",
    documentCount: 24,
    totalChunks: 1847,
    totalSize: 4_200_000,
    embeddingModel: "text-embedding-3-small",
    chunkStrategy: "recursive",
    status: "active",
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: "col-2",
    name: "Support Tickets",
    description: "Historical support tickets and resolutions from Zendesk.",
    documentCount: 156,
    totalChunks: 5230,
    totalSize: 12_800_000,
    embeddingModel: "text-embedding-3-small",
    chunkStrategy: "semantic",
    status: "active",
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: "col-3",
    name: "Engineering Wiki",
    description: "Internal engineering runbooks, ADRs, and architecture docs.",
    documentCount: 42,
    totalChunks: 3100,
    totalSize: 8_500_000,
    embeddingModel: "text-embedding-3-large",
    chunkStrategy: "recursive",
    status: "indexing",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 60000 * 15).toISOString(),
  },
  {
    id: "col-4",
    name: "Legal & Compliance",
    description: "Terms of service, privacy policies, SOC2 evidence.",
    documentCount: 8,
    totalChunks: 420,
    totalSize: 1_100_000,
    embeddingModel: "text-embedding-3-small",
    chunkStrategy: "fixed",
    status: "active",
    createdAt: new Date(Date.now() - 86400000 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
];

export const mockDocuments: Document[] = [
  {
    id: "doc-1",
    collectionId: "col-1",
    filename: "api-reference.md",
    mimeType: "text/markdown",
    size: 245_000,
    chunkCount: 182,
    status: "indexed",
    progress: 100,
    metadata: { version: "2.1", author: "engineering" },
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "doc-2",
    collectionId: "col-1",
    filename: "getting-started-guide.pdf",
    mimeType: "application/pdf",
    size: 520_000,
    chunkCount: 94,
    status: "indexed",
    progress: 100,
    metadata: { version: "1.0", author: "docs-team" },
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: "doc-3",
    collectionId: "col-1",
    filename: "deployment-runbook.md",
    mimeType: "text/markdown",
    size: 78_000,
    chunkCount: 45,
    status: "processing",
    progress: 67,
    metadata: { version: "3.0" },
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "doc-4",
    collectionId: "col-1",
    filename: "webhook-integration.pdf",
    mimeType: "application/pdf",
    size: 310_000,
    chunkCount: 0,
    status: "pending",
    progress: 0,
    metadata: {},
    createdAt: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: "doc-5",
    collectionId: "col-2",
    filename: "ticket-export-jan-2026.csv",
    mimeType: "text/csv",
    size: 2_400_000,
    chunkCount: 1240,
    status: "indexed",
    progress: 100,
    metadata: { source: "zendesk", period: "2026-01" },
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
  },
  {
    id: "doc-6",
    collectionId: "col-3",
    filename: "architecture-decision-records.md",
    mimeType: "text/markdown",
    size: 156_000,
    chunkCount: 0,
    status: "error",
    progress: 34,
    errorMessage: "Embedding API rate limit exceeded. Retry in 60s.",
    metadata: {},
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
];

export const mockSearchResults: SearchResult[] = [
  {
    id: "sr-1",
    documentId: "doc-1",
    documentName: "api-reference.md",
    collectionName: "Product Documentation",
    content:
      "The /api/v2/agents endpoint accepts POST requests with a JSON body containing the agent configuration. Required fields: name (string), model (string), system_prompt (string). Optional: tools (array), temperature (float 0-2), max_tokens (integer).",
    score: 0.94,
    chunkIndex: 42,
    metadata: { section: "API Reference", heading: "Agent Endpoints" },
  },
  {
    id: "sr-2",
    documentId: "doc-2",
    documentName: "getting-started-guide.pdf",
    collectionName: "Product Documentation",
    content:
      "To create your first agent, navigate to the dashboard and click 'New Agent'. Choose a base model, configure the system prompt, and optionally attach tools. The agent will be available via the API immediately after creation.",
    score: 0.89,
    chunkIndex: 7,
    metadata: { page: "12", section: "Quick Start" },
  },
  {
    id: "sr-3",
    documentId: "doc-5",
    documentName: "ticket-export-jan-2026.csv",
    collectionName: "Support Tickets",
    content:
      "Customer reported that agent responses were slower than expected when using GPT-4. Root cause: default max_tokens was set to 4096 causing longer generation times. Resolution: reduced to 1024 and added streaming.",
    score: 0.82,
    chunkIndex: 891,
    metadata: { ticketId: "ZD-4521", priority: "high" },
  },
  {
    id: "sr-4",
    documentId: "doc-1",
    documentName: "api-reference.md",
    collectionName: "Product Documentation",
    content:
      "Rate limits: Free tier — 100 requests/minute. Pro tier — 1,000 requests/minute. Enterprise — custom. All tiers support burst up to 2x the base rate for 10-second windows. Rate limit headers: X-RateLimit-Remaining, X-RateLimit-Reset.",
    score: 0.78,
    chunkIndex: 156,
    metadata: { section: "API Reference", heading: "Rate Limits" },
  },
  {
    id: "sr-5",
    documentId: "doc-3",
    documentName: "deployment-runbook.md",
    collectionName: "Product Documentation",
    content:
      "Production deployment checklist: 1) Run migrations 2) Verify Redis connection 3) Check ActionCable health 4) Warm embedding cache 5) Smoke test agent endpoints. Rollback: revert to previous Docker image tag.",
    score: 0.71,
    chunkIndex: 23,
    metadata: { section: "Deployment" },
  },
];
